### ISSUE TITLE
memory leak in android kitkat

### ISSUE THREAD

**Issue by krudos** [F43nd1r/rhino-android#1]
i have a memory leak when i load a file around 500kb to rhino in android kitkat
do you have tested rhino with big files in android kitkat?

**Comment by F43nd1r** [comment]
No, I haven't tested this in any bigger scale. I currently know of one app which will use this in a beta release with several thousand users soon (probably next week). Until then I don't really have access to testers. 

If you can provide additional data, like a logcat and the js file used I will try to reproduce and investigate the issue.

**Comment by F43nd1r** [comment]
Closing as no more info was provided.
