### ISSUE TITLE
xml node attribute name is always “*” 

### ISSUE THREAD

**Issue by clearw5** [F43nd1r/rhino-android#4]
The following javascript code works well and get "id" as expected on JVM. But when I run it on android with this library, I always get "*". Is it caused by the diffs between JVM and android? How can I get the expected result ? Or any other ways to get the attribute name of xml node?

   ` (<xml id="foo"></xml>).attributes()[0].name()`

**Comment by F43nd1r** [comment]
This is not a problem of this library. The scope of the project is to allow the use of optimization levels other than 0, and the use of JavaAdapter.

The Problem you describe also exists with base rhino on android.

**Comment by clearw5** [comment]
OK, I have opened a issue on base rhino repo.
