### ISSUE TITLE
Missing dependencies for org.mozilla.javascript.* in 1.5

### ISSUE THREAD

**Issue by esh0** [F43nd1r/rhino-android#5]
Hello, I've been trying to update rhino to 1.5, but seems that it doesn't include org.mozilla.javascript.* classes. On 1.4 it's all fine. Should we add this dependency separatelly to our project?

**Comment by F43nd1r** [comment]
looks like dependencies didn't make it into the 1.5 pom. I've just uploaded 1.5.1 with a fix.
