### ISSUE TITLE
Rhino closes automatically 

### ISSUE THREAD

**Issue by LucasArt95** [F43nd1r/rhino-android#6]
Hello. I am using Rhino into an android service.  I use an activity to start the service and it all works, but as soon as i exit the activity the Rhino script closes.

I have uploaded the script that I'm using and the app sources

[rhinotest.zip](https://github.com/F43nd1r/rhino-android/files/2188381/rhinotest.zip)

**Comment by F43nd1r** [comment]
Are you aware of the [Android backround execution limits](https://developer.android.com/about/versions/oreo/background#services)?

**Comment by LucasArt95** [comment]
This seems to be the problem. I tested on a 8.0 emulator and I thought it was 7.1. I just tested on 7.1 and works perfectly. I'm sorry
