### ISSUE TITLE
Reuse compiled dexes

### ISSUE THREAD

**Issue by jcrabanal** [F43nd1r/rhino-android#7]
Hello F43nd1r, this is more like a question rather than an issue, but here it goes. I have implemented a similar solution like yours in my Rhino implementation. If i'm not wrong, Rhino emits java bytecode again every time it runs an script, even if it ran it previously, then your library dexes it, then it is loaded with android's dex classloaders.

Would it be possible to store those compiled dexes, and run them directly the next time the same script is run?

I'm looking to squeeze performance by persisting those compiled scripts, so even if the app dies and restarts, it doesn't need to compile them again. Do you think this is feasible?

**Comment by F43nd1r** [comment]
It is certainly possible to do that. You'd have to associate the dex file with the source somehow, which is kind of akward, as the source isn't passed to the classloader. But it isn't impossible.

**Comment by jcrabanal** [comment]
Thought so. I'm carefully naming every script passed to rhino, so that shouldn't be a problem. The problem lies in knowing what Rhino classes should I modify to skip the bytecode generation and how.

Looks like I'll need to study the Rhino sources more. Thank you!

**Comment by F43nd1r** [comment]
Do you inted to create a pull request if you get to a solution? Otherwise I'll close this.

**Comment by jcrabanal** [comment]
Go ahead and close it.
